version: '3'

services:
  database:
    image: mysql:8.1.0
    ports:
      - '3307:3306'
    environment:
      MYSQL_DATABASE: 'home'
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - database:/var/lib/mysql

volumes:
  database:
