version: '3'

services:
  database:
    container_name: 'home-database'
    image: mysql:8.1.0
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'home'
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - home-database:/var/lib/mysql

volumes:
  home-database:
